<a href="https://colab.research.google.com/github/BAEK-SEUNGYUN/modu_deep/blob/main/nlp_5%EC%9D%BC%EC%B0%A8_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

RNN = 시퀀스 모델, 순서가 있는 나열

시퀀스 벡터 - 이러한 순서를 보존하여 벡터공간에 저장

과거의 시퀀스를 현재에 반영하는게 RNN의 특징

RNN은 입력값과 출력값이 자유롭다  일대다, 다대일, 다대다

-일대다 - 입력은 하난데 출력은 여러개 예)이미지 캡셔닝 -> 인풋으로 그림, 아웃풋으로 캡션

-다대일 - 예) 스팸메일 

-다대다 - 입력문장으로부터 대답 문장을 출력 예) 챗봇, 번역기, 개체명인식기, 품사태깅 등..



## keras 로 RNN 구현하기

In [9]:
from keras.models import Sequential
from keras.layers import SimpleRNN

In [10]:
model = Sequential()
model.add(SimpleRNN(3, input_shape=(2,10)))
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_1 (SimpleRNN)     (None, 3)                 42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [12]:
model = Sequential()
model.add(SimpleRNN(3, batch_input_shape=(8,2,10)))
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_3 (SimpleRNN)     (8, 3)                    42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [14]:
model = Sequential()
model.add(SimpleRNN(3, batch_input_shape=(8,2,10), return_sequences=True))
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_4 (SimpleRNN)     (8, 2, 3)                 42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


## 파이썬으로 RNN 구현하기

$$ h_t = tanh(W_x X_t + W_h H_{t-1} + b)$$



```
의사코드
hidden_State_t = 0
for input_t in input_length: #각 시점마다 입력을 받는다.
    output_t = tanh(input_t, hidden_stat_t) #각 시점에 대해서 입력과 은닉 상태를 가지고 연산
    hidden_stat_t = output_t # 계산결과는 현재 시점의 은닉 상태가 된다.
```

In [18]:
import numpy as np
timesteps = 10 # 시점의 수
input_dim = 4
hidden_size = 8 # 은닉 상태의 크기(메모리 셀의 용량?)

inputs = np.random.random((timesteps, input_dim))

hidden_state_t = np.zeros((hidden_size,)) # 초기 은닉 상태는 0(벡터)로 초기화
# 은닉상태의 크기 hidden size로 은닉상태를 만듬

In [19]:
print(hidden_state_t)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [23]:
Wx = np.random.random((hidden_size, input_dim)) # (8,4) 입력에 대한 가중치
Wh = np.random.random((hidden_size, hidden_size)) # (8,8) 은닉상태에 대한 가중치

b = np.random.random((hidden_size)) # (8,) 편향

In [24]:
print(np.shape(Wx))   # 은닉상태의 크기 * 입력의 차원
print(np.shape(Wh))   # 은닉상태의 크기 * 은닉상태의 크기
print(np.shape(b))    # 은닉상태의 크기

(8, 4)
(8, 8)
(8,)


In [27]:
total_hidden_state = []

# 메모리 셀 동작
for input_t in inputs:
  output_t = np.tanh(np.dot(Wx,input_t) + np.dot(Wh,hidden_state_t)+b)
  total_hidden_state.append(list(output_t))
  print(np.shape(total_hidden_state))  # 각 시점의 t별 메모리 셀의 출력의 크기는 (timesteps, output_dim)

total_hidden_state = np.stack(total_hidden_state, axis=0)
print(total_hidden_state) # (timesteps , outputdim) 크기

(1, 8)
(2, 8)
(3, 8)
(4, 8)
(5, 8)
(6, 8)
(7, 8)
(8, 8)
(9, 8)
(10, 8)
[[0.92700366 0.95670152 0.96963411 0.97655459 0.76956391 0.96926539
  0.94473721 0.9658133 ]
 [0.5901368  0.80276721 0.86178996 0.76433431 0.56101548 0.74974371
  0.66574454 0.90714879]
 [0.69562057 0.85449149 0.91965205 0.87027505 0.48153884 0.89648321
  0.73813562 0.92005441]
 [0.83786294 0.94409473 0.97071084 0.95261989 0.64212601 0.94949824
  0.89151677 0.96670607]
 [0.90385439 0.9535068  0.96748255 0.9668038  0.78546825 0.94853533
  0.9370608  0.96820556]
 [0.87863777 0.96760904 0.98003295 0.96777666 0.76042394 0.94895097
  0.9339046  0.98144033]
 [0.84166508 0.90267923 0.96182226 0.93606186 0.6795842  0.93086575
  0.90032063 0.93249438]
 [0.91331654 0.95960962 0.94239029 0.9619687  0.8715401  0.9010679
  0.94091912 0.97563232]
 [0.91456036 0.95915091 0.97189065 0.97100579 0.81061824 0.95044745
  0.94789797 0.97152319]
 [0.74736022 0.87223994 0.89604059 0.88935263 0.5410283  0.90208989
  0.74950481 0.92879099]]

## 양방향 순환 신경망

In [42]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Bidirectional

model = Sequential()
model.add(Bidirectional(SimpleRNN(hidden_size, return_sequences=True), input_shape=(timesteps, input_dim)))  # simple RNN

In [29]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bidirectional (Bidirectional (None, 10, 16)            208       
Total params: 208
Trainable params: 208
Non-trainable params: 0
_________________________________________________________________


In [34]:
# 은닉층을 쌓아보자
model = Sequential()
model.add(Bidirectional(SimpleRNN(hidden_size, return_sequences = True), input_shape=(timesteps, input_dim)))
model.add(Bidirectional(SimpleRNN(hidden_size, return_sequences=True)))
model.add(Bidirectional(SimpleRNN(hidden_size, return_sequences=True)))
model.add(Bidirectional(SimpleRNN(hidden_size, return_sequences=True)))

In [35]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bidirectional_9 (Bidirection (None, 10, 16)            208       
_________________________________________________________________
bidirectional_10 (Bidirectio (None, 10, 16)            400       
_________________________________________________________________
bidirectional_11 (Bidirectio (None, 10, 16)            400       
_________________________________________________________________
bidirectional_12 (Bidirectio (None, 10, 16)            400       
Total params: 1,408
Trainable params: 1,408
Non-trainable params: 0
_________________________________________________________________


``` 
Quiz
1. Embedding을 사용하여 단어 집합(Vocabulary)의 크기가 5,000이고, 임베딩 벡터의 차원은 100입니다.
2. 은닉층에서 Simple RNN을 사용하여 은닉상태의 크기는 128이다.
3. 훈련에 사용하는 모든 샘플의 길이는 30으로 가정
4. 이진 분류를 수행하는 모델로, 출력층의 뉴련은 1개로 시그모이드 함수를 사용
5. 은닉층은 1개

총 파라미터 갯수를 구하시오.

```
Wx = 은닉상태의 크기 * 입력의 차원

Wh = 은닉상태의 크기 * 은닉상태의 크기


Embedding = 5,000(input) * 100(embedding) = 500,000

Wx = 100(embedding) * 128(hidden) = 12,800

Wh = 128 * 128 = 16,384

bias(hidden)  = 128

Wy = 128

bias(output) = 1

total = 529,441 

In [48]:
from tensorflow.keras import layers
model = Sequential()
model.add(layers.Embedding(input_dim=5000, output_dim=100))
model.add(layers.SimpleRNN(128))
model.add(layers.Dense(1,activation='sigmoid'))

model.summary()

Model: "sequential_15"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, None, 100)         500000    
_________________________________________________________________
simple_rnn_18 (SimpleRNN)    (None, 128)               29312     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 129       
Total params: 529,441
Trainable params: 529,441
Non-trainable params: 0
_________________________________________________________________


## 임의의 입력으로 SimpleRNN과 LSTM 이해하기

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, LSTM, Bidirectional

In [3]:
train_x = [[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]
print(np.shape(train_x)) # 단어 벡터차원은 5, 문장의 길이가 4인 경우를 가정한 것

(4, 5)


In [4]:
train_x = [[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]]
train_x = np.array(train_x, dtype=np.float32)
print(train_x.shape)  # (batch_size, timesteps, imput_dim) 

(1, 4, 5)


In [5]:
rnn = SimpleRNN(3) # rnn = SimpleRNN(3, return_sequences=False, return_state=False)와 동일
hidden_state = rnn(train_x)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))

hidden state : [[ 0.6609109  -0.74089336  0.9105142 ]], shape: (1, 3)


In [6]:
rnn = SimpleRNN(3, return_sequences=True)
hidden_state = rnn(train_x)
print('hidden states : {}, shape : {}'.format(hidden_state, hidden_state.shape))

hidden states : [[[ 0.99970037 -0.77856284 -0.6117743 ]
  [ 0.9967661  -0.99862456  0.8509117 ]
  [ 0.9774142  -0.99771607  0.9772807 ]
  [ 0.9787797  -0.99630713  0.9953904 ]]], shape : (1, 4, 3)


In [7]:
rnn = SimpleRNN(3, return_sequences=True, return_state=True)
hidden_state, last_state = rnn(train_x)

print('hidden states: {}, shape:{}'.format(hidden_state, hidden_state.shape))
print('last hidden state: {}, shape : {}'.format(last_state, last_state.shape))

hidden states: [[[ 0.9764161  -0.953357   -0.6644549 ]
  [ 0.92235446 -0.9474687  -0.8186774 ]
  [ 0.98696274 -0.41896582 -0.4506324 ]
  [ 0.1471726  -0.5841303  -0.8904831 ]]], shape:(1, 4, 3)
last hidden state: [[ 0.1471726 -0.5841303 -0.8904831]], shape : (1, 3)


In [8]:
rnn = SimpleRNN(3, return_sequences=False, return_state=True)
hidden_state, last_state = rnn(train_x)

print('hidden states: {}, shape:{}'.format(hidden_state, hidden_state.shape))
print('last hidden state: {}, shape : {}'.format(last_state, last_state.shape))

hidden states: [[ 0.43626958  0.09189343 -0.96855444]], shape:(1, 3)
last hidden state: [[ 0.43626958  0.09189343 -0.96855444]], shape : (1, 3)


## LSTM 이해하기

In [15]:
lstm = LSTM(3, return_sequences=False, return_state=True)
hidden_state, last_state, last_cell_state = lstm(train_x)

print('hidden states: {}, shape:{}'.format(hidden_state, hidden_state.shape))
print('last hidden state: {}, shape : {}'.format(last_state, last_state.shape))
print('last cell state : {}, shape : {}'.format(last_cell_state, last_cell_state.shape))

hidden states: [[-0.39959276 -0.6754804  -0.23839183]], shape:(1, 3)
last hidden state: [[-0.39959276 -0.6754804  -0.23839183]], shape : (1, 3)
last cell state : [[-0.846239   -1.3075279  -0.73367035]], shape : (1, 3)


In [16]:
lstm = LSTM(3, return_sequences=True, return_state=True)
hidden_state, last_state, last_cell_state = lstm(train_x)

print('hidden states: {}, shape:{}'.format(hidden_state, hidden_state.shape))
print('last hidden state: {}, shape : {}'.format(last_state, last_state.shape))
print('last cell state : {}, shape : {}'.format(last_cell_state, last_cell_state.shape))

hidden states: [[[-0.06176076  0.01672751  0.48412633]
  [-0.10796634  0.19146031  0.27811646]
  [ 0.05934399  0.21796514 -0.0751285 ]
  [ 0.21582921  0.08530392  0.20115831]]], shape:(1, 4, 3)
last hidden state: [[0.21582921 0.08530392 0.20115831]], shape : (1, 3)
last cell state : [[0.49778485 0.14463216 0.25743014]], shape : (1, 3)


## Bidirectional (LSTM) 이해하기

In [17]:
k_init = tf.keras.initializers.Constant(value=0.1)
b_init = tf.keras.initializers.Constant(value=0)
r_init = tf.keras.initializers.Constant(value=0.1)

In [18]:
bilstm = Bidirectional(LSTM(3, return_sequences=False, return_state=True, kernel_initializer=k_init, bias_initializer=b_init, recurrent_initializer=r_init))
hidden_state, forward_h, forward_c, backward_h, backward_c = bilstm(train_x)

print('hidden states: {}, shape:{}'.format(hidden_state, hidden_state.shape))
print('forward states: {}, shape:{}'.format(forward_h, forward_h.shape))
print('backward_h states: {}, shape:{}'.format(backward_h, backward_h.shape))

hidden states: [[0.63031393 0.63031393 0.63031393 0.7038734  0.7038734  0.7038734 ]], shape:(1, 6)
forward states: [[0.63031393 0.63031393 0.63031393]], shape:(1, 3)
backward_h states: [[0.7038734 0.7038734 0.7038734]], shape:(1, 3)


In [19]:
bilstm = Bidirectional(LSTM(3, return_sequences=True, return_state=True, kernel_initializer=k_init, bias_initializer=b_init, recurrent_initializer=r_init))
hidden_state, forward_h, forward_c, backward_h, backward_c = bilstm(train_x)

print('hidden states: {}, shape:{}'.format(hidden_state, hidden_state.shape))
print('forward states: {}, shape:{}'.format(forward_h, forward_h.shape))
print('backward_h states: {}, shape:{}'.format(backward_h, backward_h.shape))

hidden states: [[[0.35906473 0.35906473 0.35906473 0.7038734  0.7038734  0.7038734 ]
  [0.5511133  0.5511133  0.5511133  0.58863586 0.58863586 0.58863586]
  [0.59115744 0.59115744 0.59115744 0.3951699  0.3951699  0.3951699 ]
  [0.63031393 0.63031393 0.63031393 0.21942244 0.21942244 0.21942244]]], shape:(1, 4, 6)
forward states: [[0.63031393 0.63031393 0.63031393]], shape:(1, 3)
backward_h states: [[0.7038734 0.7038734 0.7038734]], shape:(1, 3)


hidden state 를 보는 의미가 무엇인가요?

model을 설계하다보면 첫번째 은닉층을 가져다 쓸경우도 있고, 두번째 state를 가져다 쓸수도 있고 마지막 층을 가져다 쓸경우도 있는데, 안에 state결과값을 보면 좀더 쉽게 이해가 되서 보고 있습니다!

정확히는 이제 뒤에 배울 attention개념이 들어가면 이 hidden state를 가지고 점수를 매기기 때문에 return sequence를 True/False에 따라 hidden state가 어떻게 출력되는지 보시면 좋을 것 같습니다

그럼 hidden state 값을 보면서 알맞은 은닉층을 선택해서 사용할 수 있다는 말씀으로 이해하면 되겠네요


## RNN을 이용한 텍스트 생성(Text Generation)
- 다 대 일 (many to one)구조의 RNN을 사용하여 문맥을 반영해서 텍스트를 생성하는 모델을 만들어 보자
- '경마장에 있는 말이 뛰고 있다'
- '그의 말이 법이다'
- '가는 말이 고와야 오는 말이 곱다'

In [20]:
import pandas as pd
# 위 3문장을 재구성하면, 아래와 같이 총 11개의 샘플이 구성됨
content = [['경마장에', '있는'],['경마장에 있는','말이'],['경마장에 있는 말이', '뛰고'],['경마장에 있는 말이 뛰고','있다'],['그의','말이'],['그의 말이','법이다'],['가는', '말이'],['가는 말이','고와야'],['가는 말이 고와야','오는'],['가는 말이 고와야 오는','말이'],['가는 말이 고와야 오는 말이','곱다']]
df = pd.DataFrame(content)
df.index = ['1', '2', '3', '4', '5', '6', '7', '8', '9','10','11']
df.columns = ['X', 'y']
df

X    y
1              경마장에   있는
2           경마장에 있는   말이
3        경마장에 있는 말이   뛰고
4     경마장에 있는 말이 뛰고   있다
5                그의   말이
6             그의 말이  법이다
7                가는   말이
8             가는 말이  고와야
9         가는 말이 고와야   오는
10     가는 말이 고와야 오는   말이
11  가는 말이 고와야 오는 말이   곱다

## 데이터에 대한 이해와 전처리

In [22]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
from tensorflow.keras.utils import to_categorical

In [24]:
text ="""경마장에 있는 말이 뛰고 있다 \n
그의 말이 법이다 \n
가는 말이 고와야 오는 말이 곱다
"""

In [43]:
# 단어집합을 생성, 크기를 확인
t = Tokenizer()
t.fit_on_texts([text])
vocab_size = len(t.word_index) +1

# 케라스 토크나이저 정수 인코딩은 인덱스가 1부터 시작,
# 케라스 원-핫 인코딩에서 배열의 인덱스가 0부터 시작하기 때문에
# 배열의 크기를 실제 단어 집합의 크기보다 +1로 생성해야함 그래서 미리 +1 선언
print('단어 집합의 크기 : %d'% vocab_size)

단어 집합의 크기 : 12


vocab_size에는 11개가 들어가 있는데 왜 +1해서 vocab_size를 12로 만드나요?

ㄴ인덱스가 안맞아서 미리 1을 선언해줘서 12을 만든거에요 실제로는 11개 들어가있죠


In [44]:
print(t.word_index)

{'말이': 1, '경마장에': 2, '있는': 3, '뛰고': 4, '있다': 5, '그의': 6, '법이다': 7, '가는': 8, '고와야': 9, '오는': 10, '곱다': 11}


In [47]:
# 훈련 데이터 만들기
sequences = list()
for line in text.split('\n'):
  encoded = t.texts_to_sequences([line])[0]
  for i in range(1, len(encoded)):
    sequence = encoded[:i+1]
    sequences.append(sequence)

print('학습에 사용할 샘플의 갯수 : %d' % len(sequences))

학습에 사용할 샘플의 갯수 : 11


In [48]:
print(sequences)

[[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [6, 1], [6, 1, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10], [8, 1, 9, 10, 1], [8, 1, 9, 10, 1, 11]]


In [49]:
max_len = max(len(i) for i in sequences) # 모든 샘플에서 길이가 가장 긴 샘플의 길이 출력
print('샘플의 최대 길이 : {}'.format(max_len))

샘플의 최대 길이 : 6


In [50]:
sequences = pad_sequences(sequences, maxlen = max_len, padding='pre')

In [51]:
print(sequences)

[[ 0  0  0  0  2  3]
 [ 0  0  0  2  3  1]
 [ 0  0  2  3  1  4]
 [ 0  2  3  1  4  5]
 [ 0  0  0  0  6  1]
 [ 0  0  0  6  1  7]
 [ 0  0  0  0  8  1]
 [ 0  0  0  8  1  9]
 [ 0  0  8  1  9 10]
 [ 0  8  1  9 10  1]
 [ 8  1  9 10  1 11]]


In [54]:
sequences = np.array(sequences)
x = sequences[:, :-1]
y = sequences[:, -1]

# 리스트의 마지막 값을 제외하고 저장한 것은 x
# 리스트의 마지막 값만 저장한 것은 y, --> 레이블에 해당

In [59]:
print(x)


[[ 0  0  0  0  2]
 [ 0  0  0  2  3]
 [ 0  0  2  3  1]
 [ 0  2  3  1  4]
 [ 0  0  0  0  6]
 [ 0  0  0  6  1]
 [ 0  0  0  0  8]
 [ 0  0  0  8  1]
 [ 0  0  8  1  9]
 [ 0  8  1  9 10]
 [ 8  1  9 10  1]]


In [55]:
print(y) # 모든 샘플에 대한 레이블 출격

[ 3  1  4  5  1  7  1  9 10  1 11]


In [57]:
y = to_categorical(y, num_classes = vocab_size)

In [58]:
print(y)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


## 모델 설게하기

In [60]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

In [61]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=max_len-1))
model.add(SimpleRNN(32))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x, y, epochs=200, verbose=2)

Epoch 1/200
1/1 - 1s - loss: 2.5007 - accuracy: 0.0000e+00
Epoch 2/200
1/1 - 0s - loss: 2.4882 - accuracy: 0.0000e+00
Epoch 3/200
1/1 - 0s - loss: 2.4758 - accuracy: 0.1818
Epoch 4/200
1/1 - 0s - loss: 2.4635 - accuracy: 0.1818
Epoch 5/200
1/1 - 0s - loss: 2.4511 - accuracy: 0.1818
Epoch 6/200
1/1 - 0s - loss: 2.4386 - accuracy: 0.3636
Epoch 7/200
1/1 - 0s - loss: 2.4258 - accuracy: 0.3636
Epoch 8/200
1/1 - 0s - loss: 2.4127 - accuracy: 0.3636
Epoch 9/200
1/1 - 0s - loss: 2.3992 - accuracy: 0.4545
Epoch 10/200
1/1 - 0s - loss: 2.3852 - accuracy: 0.5455
Epoch 11/200
1/1 - 0s - loss: 2.3706 - accuracy: 0.5455
Epoch 12/200
1/1 - 0s - loss: 2.3553 - accuracy: 0.5455
Epoch 13/200
1/1 - 0s - loss: 2.3393 - accuracy: 0.5455
Epoch 14/200
1/1 - 0s - loss: 2.3225 - accuracy: 0.5455
Epoch 15/200
1/1 - 0s - loss: 2.3049 - accuracy: 0.5455
Epoch 16/200
1/1 - 0s - loss: 2.2863 - accuracy: 0.5455
Epoch 17/200
1/1 - 0s - loss: 2.2669 - accuracy: 0.3636
Epoch 18/200
1/1 - 0s - loss: 2.2465 - accuracy: 

In [136]:
# 문장을 생성하는 함수 만들어서 출력하기
def sentence_generation(model, t, current_word, n): # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word # 처음 들어온 단어도 마지막에 같이 출력하기위해 저장
    sentence = ''
    for _ in range(n): # n번 반복
        encoded = t.texts_to_sequences([current_word])[0] # 현재 단어에 대한 정수 인코딩
        encoded = pad_sequences([encoded], maxlen=5, padding='pre') # 데이터에 대한 패딩
        result = model.predict_classes(encoded, verbose=0)
    # 입력한 X(현재 단어)에 대해서 Y를 예측하고 Y(예측한 단어)를 result에 저장.
        for word, index in t.word_index.items(): 
            if index == result: # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면
                break # 해당 단어가 예측 단어이므로 break
        current_word = current_word + ' '  + word # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        sentence = sentence + ' ' + word # 예측 단어를 문장에 저장
    # for문이므로 이 행동을 다시 반복
    sentence = init_word + sentence
    return sentence

In [137]:
print(sentence_generation(model, t, '경마장에', 4))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


경마장에 walk drake tech future


In [64]:
print(sentence_generation(model, t, '그의', 2))

그의 말이 법이다


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [135]:
print(sentence_generation(model, t, '그의', 5))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


그의 comebacks your bank account interest


## LSTM 을 이용한 텍스트 생성

In [67]:
import pandas as pd
import numpy as np
from string import punctuation
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [68]:
df = pd.read_csv('/content/drive/MyDrive/dataset/ArticlesApril2018.csv')

In [69]:
df.head()

articleID  ...                                             webURL
0  5adf6684068401528a2aa69b  ...  https://www.nytimes.com/2018/04/24/sports/foot...
1  5adf653f068401528a2aa697  ...  https://www.nytimes.com/2018/04/24/climate/epa...
2  5adf4626068401528a2aa628  ...  https://www.nytimes.com/2018/04/24/dining/noma...
3  5adf40d2068401528a2aa619  ...  https://www.nytimes.com/2018/04/24/world/europ...
4  5adf3d64068401528a2aa60f  ...  https://www.nytimes.com/2018/04/24/world/canad...

[5 rows x 15 columns]

In [74]:
print('열의 갯수 : ', len(df.columns))
print(df.columns)

열의 갯수 :  15
Index(['articleID', 'articleWordCount', 'byline', 'documentType', 'headline',
       'keywords', 'multimedia', 'newDesk', 'printPage', 'pubDate',
       'sectionName', 'snippet', 'source', 'typeOfMaterial', 'webURL'],
      dtype='object')


In [88]:
# NULL 이 있는지 확인
print(df.isnull().sum())
print()
print(df['headline'].isnull().values.any())

articleID           0
articleWordCount    0
byline              0
documentType        0
headline            0
keywords            0
multimedia          0
newDesk             0
printPage           0
pubDate             0
sectionName         0
snippet             0
source              0
typeOfMaterial      0
webURL              0
dtype: int64

False


In [98]:
# headline 열에서 모든 신문 기사의 제목을 뽑아서 하나의 리스트로 저장하자
headline = []
headline.extend(list(df.headline.values)) # 헤드라인의 값들을 리스트로 저장

In [99]:
# 상위 5개만 출력
headline[:5]

['Former N.F.L. Cheerleaders’ Settlement Offer: $1 and a Meeting With Goodell',
 'E.P.A. to Unveil a New Rule. Its Effect: Less Science in Policymaking.',
 'The New Noma, Explained',
 'Unknown',
 'Unknown']

In [100]:
# 총 샘플의 개수
print('총 샘플의 개수 : {}'.format(len(headline)))

총 샘플의 개수 : 1324


In [101]:
# unknown 값을 가진 샘플 제거
# 제거 후 샘플의 갯수 출력

headline = [item for item in headline if item != 'Unknown']

In [104]:
# 상위 5개만 출력
headline[:5]


['Former N.F.L. Cheerleaders’ Settlement Offer: $1 and a Meeting With Goodell',
 'E.P.A. to Unveil a New Rule. Its Effect: Less Science in Policymaking.',
 'The New Noma, Explained',
 'How a Bag of Texas Dirt  Became a Times Tradition',
 'Is School a Place for Self-Expression?']

In [103]:

# unknown 제거한 샘플의 개수
print('unknown 제거한 샘플의 개수 : {}'.format(len(headline)))

unknown 제거한 샘플의 개수 : 1214


In [105]:
def repreprocessing(s):
  s = s.encode("utf8").decode("ascii",'ignore')
  return ''.join(c for c in s if c not in punctuation).lower() # 구두점 제거와 동시에 소문자화

text = [repreprocessing(x) for x in headline]
text[:5]

['former nfl cheerleaders settlement offer 1 and a meeting with goodell',
 'epa to unveil a new rule its effect less science in policymaking',
 'the new noma explained',
 'how a bag of texas dirt  became a times tradition',
 'is school a place for selfexpression']

In [109]:
t= Tokenizer()
t.fit_on_texts(text)
vocab_size = len(t.word_index) + 1
print('단어 집합의 크기 : %d' % vocab_size)

단어 집합의 크기 : 3494


In [108]:
sequences = list()

In [110]:
for line in text:
  encoded = t.texts_to_sequences([line])[0] #각 샘플에 대한 정수 인코딩
  for i in range(1, len(encoded)):
    sequence = encoded[:i+1]
    sequences.append(sequence)
    
sequences[:11]

[[99, 269],
 [99, 269, 371],
 [99, 269, 371, 1115],
 [99, 269, 371, 1115, 582],
 [99, 269, 371, 1115, 582, 52],
 [99, 269, 371, 1115, 582, 52, 7],
 [99, 269, 371, 1115, 582, 52, 7, 2],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372, 10],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372, 10, 1116],
 [100, 3]]

In [117]:
index_to_word = {}

for key, value in t.word_index.items(): 
  index_to_word[value] = key

print('빈도수 상위 582번 단어 : {}'.format(index_to_word[50]))

빈도수 상위 582번 단어 : recap


In [118]:
max_len = max(len(i) for i in sequences)
print('샘플의 최대 길이 : {}'.format(max_len))

샘플의 최대 길이 : 24


In [119]:
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')
print(sequences[:3])

[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0   99  269]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0   99  269  371]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0   99  269  371 1115]]


In [120]:
sequences = np.array(sequences)
x = sequences[:, :-1]
y = sequences[:, -1]

In [121]:
print(x)

[[   0    0    0 ...    0    0   99]
 [   0    0    0 ...    0   99  269]
 [   0    0    0 ...   99  269  371]
 ...
 [   0    0    0 ...  170    8 3493]
 [   0    0    0 ...    8 3493  115]
 [   0    0    0 ... 3493  115    2]]


In [122]:
print(y)

[ 269  371 1115 ...  115    2 1025]


In [123]:
y = to_categorical(y, num_classes=vocab_size)

In [124]:
print(y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


### 모델 설계

In [125]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, LSTM

In [126]:
# 한 30분 걸림

model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=max_len-1))
model.add(LSTM(128))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x,y, epochs = 200, verbose=2)

Epoch 1/200
244/244 - 11s - loss: 7.6563 - accuracy: 0.0290
Epoch 2/200
244/244 - 8s - loss: 7.1144 - accuracy: 0.0291
Epoch 3/200
244/244 - 8s - loss: 6.9743 - accuracy: 0.0343
Epoch 4/200
244/244 - 8s - loss: 6.8465 - accuracy: 0.0409
Epoch 5/200
244/244 - 8s - loss: 6.6917 - accuracy: 0.0456
Epoch 6/200
244/244 - 8s - loss: 6.5200 - accuracy: 0.0490
Epoch 7/200
244/244 - 8s - loss: 6.3240 - accuracy: 0.0525
Epoch 8/200
244/244 - 8s - loss: 6.1236 - accuracy: 0.0606
Epoch 9/200
244/244 - 8s - loss: 5.9259 - accuracy: 0.0595
Epoch 10/200
244/244 - 8s - loss: 5.7439 - accuracy: 0.0698
Epoch 11/200
244/244 - 8s - loss: 5.5745 - accuracy: 0.0706
Epoch 12/200
244/244 - 8s - loss: 5.4147 - accuracy: 0.0752
Epoch 13/200
244/244 - 8s - loss: 5.2621 - accuracy: 0.0810
Epoch 14/200
244/244 - 8s - loss: 5.1161 - accuracy: 0.0869
Epoch 15/200
244/244 - 8s - loss: 4.9772 - accuracy: 0.0930
Epoch 16/200
244/244 - 8s - loss: 4.8419 - accuracy: 0.1069
Epoch 17/200
244/244 - 8s - loss: 4.7113 - accur

In [127]:
# 문장을 생성하는 함수 만들어서 출력하기
def sentence_generation(model, t, current_word, n): # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word # 처음 들어온 단어도 마지막에 같이 출력하기위해 저장
    sentence = ''
    for _ in range(n): # n번 반복
        encoded = t.texts_to_sequences([current_word])[0] # 현재 단어에 대한 정수 인코딩
        encoded = pad_sequences([encoded], maxlen=23, padding='pre') # 데이터에 대한 패딩
        result = model.predict_classes(encoded, verbose=0)
    # 입력한 X(현재 단어)에 대해서 Y를 예측하고 Y(예측한 단어)를 result에 저장.
        for word, index in t.word_index.items(): 
            if index == result: # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면
                break # 해당 단어가 예측 단어이므로 break
        current_word = current_word + ' '  + word # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        sentence = sentence + ' ' + word # 예측 단어를 문장에 저장
    # for문이므로 이 행동을 다시 반복
    sentence = init_word + sentence
    return sentence

In [128]:
print(sentence_generation(model, t, 'i', 10))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


i cant jump ship from facebook yet fostered and stars say


In [129]:
print(sentence_generation(model, t, 'how', 10))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


how do you get your nature fix not attitudes died to


In [130]:
print(sentence_generation(model, t, 'former', 10)) 

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


former playboy model is free to discuss alleged affair in syria


In [131]:
print(sentence_generation(model, t, 'former', 5))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


former playboy model is free to
