<a href="https://colab.research.google.com/github/BAEK-SEUNGYUN/modu_deep/blob/main/modu_Sonar_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
# 드라이브에 있는 sonar.csv 데이터를 가져온다.
my_data = '/content/drive/MyDrive/dataset/sonar.csv'

In [40]:
#본문에 맞는 텐서플로 버전을 선택합니다.
# !pip install -q tensorflow-gpu==1.15.0
%tensorflow_version 1.x


In [41]:
import tensorflow as tf
import pandas as pd
import numpy as np

from keras.models import Sequential
from keras.layers.core import Dense
from sklearn.preprocessing import LabelEncoder

In [42]:
# seed 값 설정
seed = 0
np.random.seed(3)
tf.compat.v1.set_random_seed(3)

In [43]:
# 데이터 적용
df = pd.read_csv(my_data, header=None)
df

0       1       2       3       4   ...      56      57      58      59  60
0    0.0200  0.0371  0.0428  0.0207  0.0954  ...  0.0180  0.0084  0.0090  0.0032   R
1    0.0453  0.0523  0.0843  0.0689  0.1183  ...  0.0140  0.0049  0.0052  0.0044   R
2    0.0262  0.0582  0.1099  0.1083  0.0974  ...  0.0316  0.0164  0.0095  0.0078   R
3    0.0100  0.0171  0.0623  0.0205  0.0205  ...  0.0050  0.0044  0.0040  0.0117   R
4    0.0762  0.0666  0.0481  0.0394  0.0590  ...  0.0072  0.0048  0.0107  0.0094   R
..      ...     ...     ...     ...     ...  ...     ...     ...     ...     ...  ..
203  0.0187  0.0346  0.0168  0.0177  0.0393  ...  0.0065  0.0115  0.0193  0.0157   M
204  0.0323  0.0101  0.0298  0.0564  0.0760  ...  0.0034  0.0032  0.0062  0.0067   M
205  0.0522  0.0437  0.0180  0.0292  0.0351  ...  0.0140  0.0138  0.0077  0.0031   M
206  0.0303  0.0353  0.0490  0.0608  0.0167  ...  0.0034  0.0079  0.0036  0.0048   M
207  0.0260  0.0363  0.0136  0.0272  0.0214  ...  0.0040  0.0036  0.0061  0.0115   M

[208 rows x 61 columns]

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       208 non-null    float64
 1   1       208 non-null    float64
 2   2       208 non-null    float64
 3   3       208 non-null    float64
 4   4       208 non-null    float64
 5   5       208 non-null    float64
 6   6       208 non-null    float64
 7   7       208 non-null    float64
 8   8       208 non-null    float64
 9   9       208 non-null    float64
 10  10      208 non-null    float64
 11  11      208 non-null    float64
 12  12      208 non-null    float64
 13  13      208 non-null    float64
 14  14      208 non-null    float64
 15  15      208 non-null    float64
 16  16      208 non-null    float64
 17  17      208 non-null    float64
 18  18      208 non-null    float64
 19  19      208 non-null    float64
 20  20      208 non-null    float64
 21  21      208 non-null    float64
 22  22

In [45]:
df.head()

0       1       2       3       4   ...      56      57      58      59  60
0  0.0200  0.0371  0.0428  0.0207  0.0954  ...  0.0180  0.0084  0.0090  0.0032   R
1  0.0453  0.0523  0.0843  0.0689  0.1183  ...  0.0140  0.0049  0.0052  0.0044   R
2  0.0262  0.0582  0.1099  0.1083  0.0974  ...  0.0316  0.0164  0.0095  0.0078   R
3  0.0100  0.0171  0.0623  0.0205  0.0205  ...  0.0050  0.0044  0.0040  0.0117   R
4  0.0762  0.0666  0.0481  0.0394  0.0590  ...  0.0072  0.0048  0.0107  0.0094   R

[5 rows x 61 columns]

In [46]:
dataset = df.values
X = dataset[:,0:60]
Y_obj = dataset[:,60]
print(X)
print(Y_obj)

[[0.02 0.0371 0.0428 ... 0.0084 0.009 0.0032]
 [0.0453 0.0523 0.0843 ... 0.0049 0.0052 0.0044]
 [0.0262 0.0582 0.1099 ... 0.0164 0.0095 0.0078]
 ...
 [0.0522 0.0437 0.018 ... 0.0138 0.0077 0.0031]
 [0.0303 0.0353 0.049 ... 0.0079 0.0036 0.0048]
 [0.026 0.0363 0.0136 ... 0.0036 0.0061 0.0115]]
['R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 

In [47]:
# 문자열 변환
e = LabelEncoder()
e.fit(Y_obj)
Y = e.transform(Y_obj)

print(Y_obj)
print(Y)

['R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M']
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 

In [48]:
# 모델 설정
model = Sequential()
model.add(Dense(24,input_dim=60, activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [49]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_10 (Dense)             (None, 24)                1464      
_________________________________________________________________
dense_11 (Dense)             (None, 10)                250       
_________________________________________________________________
dense_12 (Dense)             (None, 1)                 11        
Total params: 1,725
Trainable params: 1,725
Non-trainable params: 0
_________________________________________________________________


In [50]:
# 모델 컴파일
model.compile(loss = 'mean_squared_error',
              optimizer='adam',
              metrics=['accuracy'])

In [51]:
# 모델 실행
model.fit(X,Y, epochs=200, batch_size=5)

Epoch 1/200
208/208 [==============================] - 0s 773us/step - loss: 0.2449 - accuracy: 0.5673
Epoch 2/200
208/208 [==============================] - 0s 292us/step - loss: 0.2404 - accuracy: 0.5481
Epoch 3/200
208/208 [==============================] - 0s 347us/step - loss: 0.2268 - accuracy: 0.6202
Epoch 4/200
208/208 [==============================] - 0s 298us/step - loss: 0.2188 - accuracy: 0.6394
Epoch 5/200
208/208 [==============================] - 0s 271us/step - loss: 0.2102 - accuracy: 0.7019
Epoch 6/200
208/208 [==============================] - 0s 300us/step - loss: 0.2019 - accuracy: 0.7212
Epoch 7/200
208/208 [==============================] - 0s 312us/step - loss: 0.1938 - accuracy: 0.7356
Epoch 8/200
208/208 [==============================] - 0s 294us/step - loss: 0.1852 - accuracy: 0.7692
Epoch 9/200
208/208 [==============================] - 0s 308us/step - loss: 0.1776 - accuracy: 0.7981
Epoch 10/200
208/208 [==============================] - 0s 326us/step - l

In [52]:
print('Accuracy : %.4f' % model.evaluate(X,Y)[1])

208/208 [==============================] - 0s 237us/step
Accuracy : 1.0000


과적합 : 모델이 학습 데이터셋 안에서는 일정 수준 이상의 예측 정확도를 보이지만, 새로운 데이터에 적용하면 잘 맞지 않는 것

과적합을 방지하려면 -> 학습 데이터셋, 테스트 데이터셋으로 분리

학습과 동시에 테스트를 병행하며 진행하는 것이 한 방법


x데이터와 y 데이터에서 각각 정해진 비율만큼 구분하여 한 그룹은 학습에 사용하고 다른 한 그룹은 테스트에 사용하게 하는 함수가 sklearn 라이브러리의 **train_test_split()** 함수

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
# seed 값 설정
seed = 0
np.random.seed(seed)
tf.compat.v1.set_random_seed(3)

In [55]:
#데이터 적용
df = pd.read_csv(my_data, header=None)

In [56]:
dataset = df.values
X = dataset[:,0:60]
Y_obj = dataset[:,60]

e = LabelEncoder()
e.fit(Y_obj)
Y = e.transform(Y_obj)

In [57]:
# 학습셋과 테스트셋의 구분

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.3, random_state=seed)

In [58]:
model = Sequential()
model.add(Dense(24,  input_dim=60, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [59]:
model.compile(loss='mean_squared_error',
            optimizer='adam',
            metrics=['accuracy'])

In [60]:
model.fit(X_train, Y_train, epochs=130, batch_size=5)

Epoch 1/130
145/145 [==============================] - 0s 1ms/step - loss: 0.2486 - accuracy: 0.5379
Epoch 2/130
145/145 [==============================] - 0s 281us/step - loss: 0.2344 - accuracy: 0.5931
Epoch 3/130
145/145 [==============================] - 0s 298us/step - loss: 0.2233 - accuracy: 0.7241
Epoch 4/130
145/145 [==============================] - 0s 263us/step - loss: 0.2125 - accuracy: 0.6966
Epoch 5/130
145/145 [==============================] - 0s 276us/step - loss: 0.2040 - accuracy: 0.7310
Epoch 6/130
145/145 [==============================] - 0s 279us/step - loss: 0.1968 - accuracy: 0.7793
Epoch 7/130
145/145 [==============================] - 0s 268us/step - loss: 0.1877 - accuracy: 0.7655
Epoch 8/130
145/145 [==============================] - 0s 290us/step - loss: 0.1772 - accuracy: 0.7379
Epoch 9/130
145/145 [==============================] - 0s 307us/step - loss: 0.1660 - accuracy: 0.7931
Epoch 10/130
145/145 [==============================] - 0s 340us/step - los

In [61]:
# 테스트셋에 모델적용

print("\n Test Accuracy : %.4f" %(model.evaluate(X_test, Y_test)[1]))

63/63 [==============================] - 0s 885us/step

 Test Accuracy : 0.7778


# 모델 저장과 재사용

학습이 끝난 후 테스트해 본 결과가 만족스러울 때 이를 모델로 저장하여 새로운 데이터에 사용할 수 있다.


In [62]:
from keras.models import load_model

model.fit(X_train, Y_train, epochs=130, batch_size=5)
model.save('my_model.h5')  # 모델을 컴퓨터에 저장

del model       # 테스트를 위해 메모리 내의 모델을 삭제
# model = load('./my_model.h5') # 모델을 새로 불러옴 -> 210620 안되는 코드 / 아래가 대안 코드
# new_model = tf.keras.models.load_model('my_model.h5') -> 그래도 되지 않는다..

'''
hyp5 버전을 낮추면 되네요

pip install h5py==2.10.0

으로 h5py의 버전을 낮추면 실행이 됩니다.

hyp5 의 버젼을 낮추면 해결되는 문제라고 한다.
'''

print("\n Test Accuracy: %.4f" % (new_model.evaluate(X_test, Y_test)[1]))  # 불러온 모델로 테스트 실행



Epoch 1/130
145/145 [==============================] - 0s 332us/step - loss: 0.0052 - accuracy: 1.0000
Epoch 2/130
145/145 [==============================] - 0s 260us/step - loss: 0.0048 - accuracy: 1.0000
Epoch 3/130
145/145 [==============================] - 0s 294us/step - loss: 0.0050 - accuracy: 1.0000
Epoch 4/130
145/145 [==============================] - 0s 301us/step - loss: 0.0047 - accuracy: 1.0000
Epoch 5/130
145/145 [==============================] - 0s 265us/step - loss: 0.0051 - accuracy: 1.0000
Epoch 6/130
145/145 [==============================] - 0s 298us/step - loss: 0.0040 - accuracy: 1.0000
Epoch 7/130
145/145 [==============================] - 0s 285us/step - loss: 0.0035 - accuracy: 1.0000
Epoch 8/130
145/145 [==============================] - 0s 299us/step - loss: 0.0043 - accuracy: 1.0000
Epoch 9/130
145/145 [==============================] - 0s 315us/step - loss: 0.0055 - accuracy: 1.0000
Epoch 10/130
145/145 [==============================] - 0s 295us/step - l

AttributeError: ignored